# Generated by Django 3.1.1 on 2020-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201001_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemsJson', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
